export const REQUEST_LOGIN_PENDING = 'REQUEST_LOGIN_PENDING';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';
export const ROUTE_CHANGE = 'ROUTE_CHANGE';
export const REQUEST_DATA_PENDING = 'REQUEST_DATA_PENDING';
export const REQUEST_DATA_FAILED = 'REQUEST_DATA_FAILED';
export const REQUEST_ADD_JOURNEY_SUCCESS = 'REQUEST_ADD_JOURNEY_SUCCESS';
export const REQUEST_UPDATE_JOURNEY_SUCCESS = 'REQUEST_UPDATE_JOURNEY_SUCCESS';
