export const REQUEST_LOGIN_PENDING = 'REQUEST_LOGIN_PENDING';
export const REQUEST_LOGIN_SUCESS = 'REQUEST_LOGIN_SUCESS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';
export const ROUTE_CHANGE = 'ROUTE_CHANGE';
